### ISSUE TITLE
Не подгружается компонент

### ISSUE THREAD

**Issue by enemy-senator92** [CookiesEater/vue-yandex-share#1]
Не так давно заметил что компонент перестал отрабатывать, и отдаёт вот такую ошибку https://c2n.me/3V2gHin
Причём и на страничке демонстраций плагина тоже

**Comment by CookiesEater** [comment]
Приветствую!

Нашёл в чём была причина и сделал изменения
Если есть возможность, то подтвердите, пожалуйста, что всё работает

**Comment by enemy-senator92** [comment]
Да спасибо всё завелось 👍

**Comment by CookiesEater** [comment]
Благодарю!
